language: python
python:
  - "2.6"
  - "2.7"

env:
  - DJANGO="Django==1.4.9"
  - DJANGO="Django==1.5.5"
  - DJANGO="https://www.djangoproject.com/download/1.6c1/tarball/"

# command to install dependencies
install: pip install $DJANGO --use-mirrors

# command to run tests
script: ./run_tests.sh

