language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO="Django==1.5.5"
  - DJANGO="Django==1.6.2"

# command to install dependencies
install: pip install $DJANGO --use-mirrors

# command to run tests
script: ./run_tests.sh

